# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    user: "1000:1000"
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./db:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro
    ports:
      - 5432:5432

